  email:
    name: Send SonarQube Report via Email
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download SonarQube Report Artifact
        uses: actions/download-artifact@v2
        with:
          name: sonarqube-report
          path: /home/runner/work/_temp/sonar-scanner/
      - name: Send SonarQube Report via Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: yashpareek.amy119@gmail.com
          password: seoa fhxg bmcg edqj
          subject: SonarQube Report
          body: email-body.txt
          to: niharika.kadellabs@gmail.com
          from: yashpareek.amy119@gmail.com
          attachments: /home/runner/work/_temp/sonar-scanner/*
          content_type: text/plain
