name: SonarQube Analysis

on:
  push:
    branches:
      - master

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch SonarQube Analysis Details
        run: |
          sonarAnalysisDetails=$(curl -u sqp_4fc120412286d7166c7d5db5f06ea1b875aed405:http://3.82.235.235:9000/api/issues/search?componentKeys=testing-sonar&resolved=false)
          echo "$sonarAnalysisDetails" > sonar-analysis-details.json

      - name: Parse SonarQube JSON to HTML
        run: |
          reportHtml='<html><body>'
          issues=$(jq -c '.issues[]' sonar-analysis-details.json)
          for issue in $issues; do
            message=$(echo $issue | jq -r '.message')
            severity=$(echo $issue | jq -r '.severity')
            component=$(echo $issue | jq -r '.component')
            rule=$(echo $issue | jq -r '.rule')
            reportHtml+="<p>Issue: $message</p><p>Severity: $severity</p><p>Component: $component</p><p>Rule: $rule</p>"
          done
          reportHtml+='</body></html>'
          echo "$reportHtml" > sonar-analysis-report.html

      - name: Archive SonarQube Analysis Report
        uses: actions/upload-artifact@v2
        with:
          name: sonarqube-report
          path: sonar-analysis-report.html

      - name: Send Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: SonarQube Report
          body: 'Please find the SonarQube Analysis report attached.'
          to: 'niharika.kadellabs@gmail.com'
          attachments: sonar-analysis-report.html
