name: Build and SonarQube Scan

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          EXTRA_ARGS: '-Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacoco.xml'  # Change this line based on your project setup

      - name: Upload SonarQube Report
        uses: actions/upload-artifact@v2
        with:
          name: sonarqube-report
          path: .scannerwork

      - name: Download SonarQube Report
        uses: actions/download-artifact@v2
        with:
          name: sonarqube-report
          path: downloaded-artifacts

      - name: List Downloaded Files
        run: ls -R downloaded-artifacts

      - name: Print SonarQube Directory Contents
        run: ls -R .scannerwork
