name: Build and SonarQube Scan

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Build and Test
        run: |
          # Replace this command with the actual build and test command for your project
          mvn clean install

      - name: SonarQube Scan
        run: |
          # Replace this command with the actual SonarQube scan command for your project
          sonar-scanner -Dsonar.projectKey=testing-sonar -Dsonar.sources=.

      - name: Create email body
        run: echo "SonarQube report is ready" > email-body.txt

      - name: Send Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: SonarQube Report
          body: email-body.txt
          to: niharika.kadellabs@gmail.com
          from: ${{ secrets.GMAIL_USER }}
