name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Install msmtp
      - name: Install msmtp
        run: |
          sudo apt-get update
          sudo apt-get install -y msmtp

      # Create msmtp configuration
      - name: Create msmtp config
        run: |
          echo "defaults" > ~/.msmtprc
          echo "auth on" >> ~/.msmtprc
          echo "tls on" >> ~/.msmtprc
          echo "tls_starttls on" >> ~/.msmtprc
          echo "tls_trust_file /etc/ssl/certs/ca-certificates.crt" >> ~/.msmtprc
          echo "logfile ~/.msmtp.log" >> ~/.msmtprc
          echo "account default" >> ~/.msmtprc
          echo "host smtp.gmail.com" >> ~/.msmtprc
          echo "port 587" >> ~/.msmtprc
          echo "from $GMAIL_USER" >> ~/.msmtprc
          echo "user $GMAIL_USER" >> ~/.msmtprc
          echo "password $GMAIL_APP_PASSWORD" >> ~/.msmtprc
          chmod 600 ~/.msmtprc

      # Send an email using msmtp
      - name: Send Email
        run: |
          echo "Subject: SonarQube Report" > email.txt
          echo "SonarQube report is ready" >> email.txt
          msmtp yashpareek.amy119@gmail.com < email.txt
        env:
          GMAIL_USER: yashpareek.amy119@gmail.com
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
