name: Scan and Notify

on:
  push:
    branches:
      - master

jobs:
  scan-and-notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SonarQube
      uses: SonarSource/sonarqube-scan-action@v2
      with:
        token: ${{ secrets.SONAR_TOKEN }}

    - name: Send email notification
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_PASSWORD }}
        subject: 'SonarQube Scan Results'
        to: 'niharika.kadellabs@gmail.com'
        body: |
          The SonarQube scan has been completed.

          Check the results here: http://3.82.235.235:9000/project/activity?id=testing-sonar
