name: Deploy PHP Application

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  deploy:
    name: Deploy to Ubuntu Server
    runs-on: ubuntu-latest

    steps:
      # Checkout the code to the runner
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH keys
      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Deploy the application to the Ubuntu server using SCP
      - name: Deploy to Ubuntu Server
        run: |
          scp -r -o StrictHostKeyChecking=no ${{ github.workspace }} ubuntu@43.205.240.212:/var/www/html/
