name: Deploy PHP Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Ubuntu Server
    runs-on: ubuntu-latest

    steps:
      # Checkout the code to the runner
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy the application to the Ubuntu server using SSH
      - name: Deploy to Ubuntu Server
        uses: easingthemes/ssh-deploy@v2
        with:
          server: 43.205.240.212
          port: 22
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: .  
          remote_path: /var/www/html  
